import firebase_admin
from firebase_admin import credentials
from firebase_admin import db

cred = credentials.Certificate("serviceAccountKey.json")
firebase_admin.initialize_app(
    cred,
    {
        "databaseURL": "https://facerecognition-b74ff-default-rtdb.firebaseio.com/",
        # database URL
    },
)

ref = db.reference("Students")  
# reference path to our database... will create student directory in the database

data = {
    "004223": {  # id of student which is a key
        "id": "004223",
        "name": "Samrat Thapa",
        "password": "004223Samrat",
        "dob": "1997-08-02",
        "address": "Barrie, Ontario",
        "phone": "2348657951",
        "email": "samratthapa@gmail.com",
        "major": "Data Science",
        "starting_year": 2020,
        "standing": "G",
        "total_attendance": 4,
        "year": 2,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "This section aims to offer essential guidance for students to successfully complete the course. It will be regularly updated \
                to ensure its relevance and usefulness. Stay tuned for valuable \
                insights and tips that will help you excel in your studies.",
    },
    "XM01": { 
        "id": "XM",
        "name": "Nguyễn Thị Xuân Mai",
        "password": "XM",
        "dob": "7-03-2004",
        "address": "Quận 12",
        "phone": "123456789",
        "email": "congaxuanmai@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng bét",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
    "XM02": { 
        "id": "XM",
        "name": "Nguyễn Thị Xuân Mai",
        "password": "XM",
        "dob": "7-03-2004",
        "address": "Quận 12",
        "phone": "123456789",
        "email": "congaxuanmai@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng bét",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
    "XM03": { 
        "id": "XM",
        "name": "Nguyễn Thị Xuân Mai",
        "password": "XM",
        "dob": "7-03-2004",
        "address": "Quận 12",
        "phone": "123456789",
        "email": "congaxuanmai@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng bét",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
    "XM04": { 
        "id": "XM",
        "name": "Nguyễn Thị Xuân Mai",
        "password": "XM",
        "dob": "7-03-2004",
        "address": "Quận 12",
        "phone": "123456789",
        "email": "congaxuanmai@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng bét",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },

    ####KN
     "KN01": { 
        "id": "KN",
        "name": "Nguyễn Trần Khánh Ngọc",
        "password": "KN",
        "dob": "7-03-2004",
        "address": "Quận 12",
        "phone": "123456789",
        "email": "kn@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "KN02": { 
        "id": "KN",
        "name": "Nguyễn Trần Khánh Ngọc",
        "password": "KN",
        "dob": "7-03-2004",
        "address": "Quận 12",
        "phone": "123456789",
        "email": "kn@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "KN03": { 
        "id": "KN",
        "name": "Nguyễn Trần Khánh Ngọc",
        "password": "KN",
        "dob": "7-03-2004",
        "address": "Quận 12",
        "phone": "123456789",
        "email": "kn@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "KN04": { 
        "id": "KN",
        "name": "Nguyễn Trần Khánh Ngọc",
        "password": "KN",
        "dob": "7-03-2004",
        "address": "Quận 12",
        "phone": "123456789",
        "email": "kn@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "KN05": { 
        "id": "KN",
        "name": "Nguyễn Trần Khánh Ngọc",
        "password": "KN",
        "dob": "7-03-2004",
        "address": "Quận 12",
        "phone": "123456789",
        "email": "kn@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },

    ##########HS
     "HS": { 
        "id": "HS",
        "name": "Vũ Hoàng Sơn",
        "password": "HS",
        "dob": "7-03-2004",
        "address": "Tân Phú",
        "phone": "123456789",
        "email": "hs@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
    ############MD
     "MD02": { 
        "id": "MD",
        "name": "Lê Minh Đức",
        "password": "MD",
        "dob": "7-03-2004",
        "address": "Tân Phú",
        "phone": "123456789",
        "email": "MD@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "MD04": { 
        "id": "MD",
        "name": "Lê Minh Đức",
        "password": "MD",
        "dob": "7-03-2004",
        "address": "Tân Phú",
        "phone": "123456789",
        "email": "MD@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "MD05": { 
        "id": "MD",
        "name": "Lê Minh Đức",
        "password": "MD",
        "dob": "7-03-2004",
        "address": "Tân Phú",
        "phone": "123456789",
        "email": "hs@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },

    ###############QA
     "QA01": { 
        "id": "QA",
        "name": "Quốc Anh",
        "password": "QA",
        "dob": "7-03-2004",
        "address": "Tân Phú",
        "phone": "123456789",
        "email": "qa@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "QA02": { 
        "id": "QA",
        "name": "Quốc Anh",
        "password": "QA",
        "dob": "7-03-2004",
        "address": "Tân Phú",
        "phone": "123456789",
        "email": "qa@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "QA03": { 
        "id": "QA",
        "name": "Quốc Anh",
        "password": "QA",
        "dob": "7-03-2004",
        "address": "Tân Phú",
        "phone": "123456789",
        "email": "qa@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "QA04": { 
        "id": "QA",
        "name": "Quốc Anh",
        "password": "QA",
        "dob": "7-03-2004",
        "address": "Tân Phú",
        "phone": "123456789",
        "email": "qa@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
     "QA05": { 
        "id": "QA",
        "name": "Quốc Anh",
        "password": "QA",
        "dob": "7-03-2004",
        "address": "Tân Phú",
        "phone": "123456789",
        "email": "qa@gmail.com",
        "major": "Công Nghệ Thông Tin",
        "starting_year": 2022,
        "standing": "Hạng A",
        "total_attendance": 4,
        "year": 3,
        "last_attendance_time": "2023-02-21 12:33:10",
        "content": "Học Viện Hàng Không",
    },
    
}


for key, value in data.items():
    ref.child(key).set(value)
